export const phones = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    brand: "Apple",
    price: 999,
    storage: "256GB",
    ram: "8GB",
    os: "iOS",
    features: ["5G", "Face ID", "Triple Camera"],
    screenSize: "6.1 inches",
    battery: "3200mAh",
    color: ["Graphite", "Silver", "Gold"],
    launchYear: 2023,
    image: "/images/iphone-15-pro.png",
    customerRating: 4.8,
  },
  {
    id: 2,
    name: "Galaxy S23 Ultra",
    brand: "Samsung",
    price: 1199,
    storage: "512GB",
    ram: "12GB",
    os: "Android",
    features: ["5G", "S Pen", "Quad Camera"],
    screenSize: "6.8 inches",
    battery: "5000mAh",
    color: ["Phantom Black", "Green", "Cream"],
    launchYear: 2023,
    image: "/images/galaxy-s23-ultra.png",
    customerRating: 4.7,
  },
  {
    id: 3,
    name: "OnePlus 11",
    brand: "OnePlus",
    price: 699,
    storage: "256GB",
    ram: "8GB",
    os: "Android",
    features: ["5G", "Hasselblad Camera"],
    screenSize: "6.7 inches",
    battery: "5000mAh",
    color: ["Titan Black", "Eternal Green"],
    launchYear: 2023,
    image: "/images/oneplus-11.png",
    customerRating: 4.6,
  },
  {
    id: 4,
    name: "Xiaomi 13 Pro",
    brand: "Xiaomi",
    price: 899,
    storage: "512GB",
    ram: "12GB",
    os: "Android",
    features: ["5G", "Leica Camera"],
    screenSize: "6.73 inches",
    battery: "4820mAh",
    color: ["Ceramic White", "Ceramic Black"],
    launchYear: 2023,
    image: "/images/xiaomi-13-pro.png",
    customerRating: 4.5,
  },
  {
    id: 5,
    name: "Google Pixel 8",
    brand: "Google",
    price: 699,
    storage: "128GB",
    ram: "8GB",
    os: "Android",
    features: ["5G", "Google Tensor G3"],
    screenSize: "6.2 inches",
    battery: "4350mAh",
    color: ["Obsidian", "Lemongrass", "Snow"],
    launchYear: 2023,
    image: "/images/pixel-8.png",
    customerRating: 4.4,
  },
  {
    id: 6,
    name: "Realme GT 3",
    brand: "Realme",
    price: 549,
    storage: "256GB",
    ram: "12GB",
    os: "Android",
    features: ["5G", "SuperVOOC Charging"],
    screenSize: "6.74 inches",
    battery: "4600mAh",
    color: ["Booster Black", "Pulse White"],
    launchYear: 2023,
    image: "/images/realme-gt-3.png",
    customerRating: 4.3,
  },
  {
    id: 7,
    name: "Vivo X90 Pro",
    brand: "Vivo",
    price: 1199,
    storage: "512GB",
    ram: "12GB",
    os: "Android",
    features: ["5G", "Zeiss Camera"],
    screenSize: "6.78 inches",
    battery: "4870mAh",
    color: ["Legend Black"],
    launchYear: 2023,
    image: "/images/vivo-x90-pro.png",
    customerRating: 4.6,
  },
  {
    id: 8,
    name: "Motorola Edge 40 Pro",
    brand: "Motorola",
    price: 799,
    storage: "256GB",
    ram: "12GB",
    os: "Android",
    features: ["5G", "144Hz Display"],
    screenSize: "6.67 inches",
    battery: "4600mAh",
    color: ["Interstellar Black", "Eclipse Blue"],
    launchYear: 2023,
    image: "/images/motorola-edge-40-pro.png",
    customerRating: 4.4,
  },
  {
    id: 9,
    name: "Oppo Reno 10",
    brand: "Oppo",
    price: 399,
    storage: "128GB",
    ram: "6GB",
    os: "Android",
    features: ["5G", "Camera"],
    screenSize: "6.7 inches",
    battery: "4600mAh",
    color: ["Glossy Purple", "Silvery Grey"],
    launchYear: 2023,
    image: "/images/oppo-reno-10.png",
    customerRating: 4.3,
  },
  {
    id: 10,
    name: "Asus ROG Phone 7",
    brand: "Asus",
    price: 1399,
    storage: "512GB",
    ram: "16GB",
    os: "Android",
    features: ["5G", "Gaming", "144Hz AMOLED"],
    screenSize: "6.78 inches",
    battery: "6000mAh",
    color: ["Phantom Black", "Storm White"],
    launchYear: 2023,
    image: "/images/asus-rog-phone-7.png",
    customerRating: 4.8,
  },
];
